apiVersion: v1
kind: Namespace
metadata:
  name: gitops-db2-oltp
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-db2-oltp-operator-group
  namespace: gitops-db2-oltp
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-db2-oltp
---
