apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-operators-ibm-entitlement-key
spec:
  destination:
    namespace: cpd-operators
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cpd-operators/ibm-entitlement-key
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-db2-oltp
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
