apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-ibm-common-services
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/ibm-common-services/namespace
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-db2-oltp
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
