apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: ibm-common-services
spec:
  encryptedData:
    .dockerconfigjson: AgCq6dgutPdvmOGjBbucZKziIKQmLjT2vz7OdxUUmgwkhsCmLCBKoET/bqApjkCigJ62wAqMSNdJ8+t8d9aeOA1MKUjZANd+p7iPwyco9hYGexyrLRS8bfZLPO7ury9H4U8IiLwKAXml2MFIPhQXNGnivltcgCwiBEL6hLqhsI69+kwHPUyuWYaZ9Pw5BCTK98TZTzuoKxz+npOo+tmFHj8aI9jrbaqH0teSMqwL7K2hL4awNIOTaIj4WGyZMKmPzGx9y/u2sc32G0z3rumVoI3Z/SsKzE1Fuke93uc0Rf02p6XTjvSi8zY2TpPm0Z/vG7vUOAfkNn6SLCIO7lCP4z+k4minDaMKppVjsyxmYv4zoHI5Q8F/vH3eRQ40qiGzHes8pZ3S4n4DRngirrAkxSQ/FH4V+P19YN+I8nONfMzfpriGN5gRZkNIw6AjNc1qO5E07AlVttShKoHHoraDoIYr9Mfd53G7h9ve7T+DisXdc4AzjN1A+xO0MMs+K6YFBE/F3sKWkivnXs2oAI0YzWTnciCsM0h6CavlaogInPe6V6MPTBsPRQEOtsW9cr5J0n2XJp+klUf6yg9krLXeoH6EcbKr1TXff9pihdIuWClQjfwHKkSv9w1nhg0ovx6DnGLr1Ae3I51WmCehvGyqzFR3WYRXdPMQsY8vxqlKhxn6wslUXtuwYhrl3J7UUpRFm6/N8F9XCduKO7+Dbcln7GTCErR9F9eA0dGZ2yHRs62zGaA9RwK9G3aoNaXNbx1bAW3dUMufhyYtQInXruSIHJtLKJW7LPGXPJo6hOq/6mrdsHq/Eh22JK4o5kte0dnHfKDjQFftyhfvt8rMwT/8wRuwTiiCDqbE45/5EmTxSrA4xygYQll6S8xoEdvFKKS0F5wuf+yrGirfrZtT1pmjRfG/bFGfEruNw+fnduvOrp87ZW1vWcj1QLM+It2Kznniad5opCSS/oRL8yXE8GSZ3Urizb9dPXwRVY93RLs3jtRQXae3AKui2LVrCJfaWBv3RBkEwysCi3j4QCwDfO4evdBl+cmV1GSxx8ES/vTD1wbpDoTfzLfoSj64QIIaz2RMcun+Yy0kO0B2ERQyfJip1GpPGuo805j1kZ09eowbNOgbeObXCzoVPWo4Jt9QC+EaunVwGEKu/YCTsaDxG825RXLhW5o2Jpsu0//68TdyX2MCysYzYrMlUbW3n523QNbBvkXVebDAUxrfSKUZZLn4EAbaBE7bVZ4vlc2dh+3PWx4lDE17NiETQdwBbRw4WThkDNP//1LfhJXlGxBI/ga6XYBLXE7hUm26BC3kh7WJ234abg3ScgHj89K52dNxu8ZeNy5r
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: ibm-common-services
    type: kubernetes.io/dockerconfigjson

